### ISSUE TITLE
Starter @ Hydration Slider

### ISSUE THREAD

**Issue by minisquid** [joshuacronemeyer/Flour-and-Water#1]
if you push the (g) slider (far right slider) to the left the two sliders become linked thus locking the at a low point of 90%

**Comment by joshuacronemeyer** [comment]
I think this is resolved. I did a revamp awhile back so the calculator would work with touchscreens and the newer drag/drop libraries are just superior. If the starter hydration slider intercepts the starter mass slider you can now easily just slide the starter mass out of the way to re-grab the hydration. Also the recent improvements by @apers makes it even easier since the text can't get in the way of the click/touch events anymore.
